### ISSUE TITLE
The build failed,please check if the correct Create table SQL is copied

### ISSUE THREAD

**Issue by CnYouth** [liujingtech/IntelliJ-MySQL-Table-to-JPA-Entity#1]
提示“The build failed,please check if the correct Create table SQL is copied”，如果处理？

**Comment by liujingtech** [comment]
你在使用之前需要将你的sql复制进剪贴板；
如果复制了还有问题，看一下sql格式是不是没有完全复制；
如果还有问题，把sql到这里我来看看。
